spring.application.name=expense-tracker-api
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

jwt.secret.key=NDQ1MzU2NDU2NDU2NDU2MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1MzQ1
jwt.time.expiration=86400000